export default {
	theme: {
		style1: {
			css_theme_style: 	'vertical-menu-template',
			css_theme_file: 	'/assets/app-assets/css/core/menu/menu-types/vertical-menu.css',
			css_body: 			'BODY STYLE1 vertical-layout vertical-menu 2-columns fixed-navbar pace-done menu-expanded',
			css_nav_top: 		'TOP header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-light bg-info navbar-shadow',
			css_nav_left: 		'LEFT main-menu menu-fixed menu-light menu-accordion    menu-shadow ',
			css_nav_right: 		'',
		},
		style2: {
			css_theme_style: 'vertical-collapsed-menu',
			css_theme_file: '/assets/app-assets/css/core/menu/menu-types/vertical-menu-modern.css',
			css_body: 'BODY STYLE2 vertical-layout vertical-menu-modern vertical-collapsed-menu 2-columns fixed-navbar pace-done menu-expanded',
			css_nav_top: 'TOP header-navbar navbar-expand-lg navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-dark navbar-shadow',
			css_nav_left: 'LEFT main-menu menu-fixed menu-dark menu-accordion menu-shadow expanded',
			css_nav_right: '',
		},
		style3: {
			css_theme_style: 'vertical-content-menu-template',
			css_theme_file: '/assets/app-assets/css/core/menu/menu-types/vertical-content-menu.css',
			css_body: 'BODY STYLE3 vertical-layout vertical-content-menu 2-columns fixed-navbar pace-done menu-expanded',
			css_nav_top: 'TOP header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-light navbar-hide-on-scroll navbar-border navbar-shadow navbar-brand-center headroom',
			css_nav_left: 'LEFT main-menu menu-static menu-light menu-accordion menu-shadow',
			css_nav_right: '',
		},
		style4: {
			css_theme_style: 'material-vertical-collapsed-menu-template',
			css_theme_file: '/assets/app-assets/css/core/menu/menu-types/material-vertical-menu-modern.css',
			css_body: 'BODY STYLE4 vertical-layout vertical-menu-modern material-vertical-layout material-layout vertical-collapsed-menu 2-columns fixed-navbar pace-done menu-expanded',
			css_nav_top: 'TOP header-navbar navbar-expand-lg navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-dark navbar-shadow',
			css_nav_left: 'LEFT main-menu material-menu menu-fixed menu-dark menu-accordion menu-shadow expanded',
			css_nav_right: '',
		},
		style5: {
			css_theme_style: 'material-vertical-menu-template',
			css_theme_file: '/assets/app-assets/css/core/menu/menu-types/material-vertical-menu.css',
			css_body: 'BODY STYLE5 vertical-layout vertical-menu material-vertical-layout material-layout 2-columns fixed-navbar pace-done menu-expanded',
			css_nav_top: 'TOP header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-light bg-primary navbar-shadow',
			css_nav_left: 'LEFT main-menu material-menu menu-fixed menu-light menu-accordion    menu-shadow ',
			css_nav_right: '',
		},
		style6: {
			css_theme_style: 'material-vertical-compact-menu-template',
			css_theme_file: 	'/assets/app-assets/css/core/menu/menu-types/material-vertical-menu-modern.css',
			css_body: 			'BODY STYLE6 css_body vertical-layout vertical-menu-modern material-vertical-layout material-layout vertical-collapsed-menu 2-columns fixed-navbar  menu-collapsed pace-done',
			css_nav_top: 		'TOP css_nav_top header-navbar navbar-expand-lg navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-dark navbar-shadow',
			css_nav_left: 		'LEFT css_nav_left main-menu material-menu menu-fixed menu-dark menu-accordion menu-shadow',
			css_nav_right: 		'',
		},
		style7: {
			css_theme_style: 'material-vertical-content-menu-template',
			css_theme_file: 	'/assets/app-assets/css/core/menu/menu-types/material-vertical-menu-modern.css',
			css_body: 'BODY STYLE7 vertical-layout vertical-content-menu material-vertical-layout material-layout 2-columns fixed-navbar pace-done menu-expanded',
			css_nav_top: 'TOP header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-light navbar-hide-on-scroll navbar-border navbar-shadow navbar-brand-center headroom',
			css_nav_left: 'LEFT main-menu material-menu menu-static menu-light menu-accordion menu-shadow',
			css_nav_right: '',
		},
		style8: {
			css_theme_style: 'material-vertical-overlay-menu-template',
			css_theme_file: '/assets/app-assets/css/core/menu/menu-types/material-vertical-overlay-menu.css',
			css_body: 'BODY STYLE8 vertical-layout vertical-overlay-menu material-vertical-layout material-layout 2-columns fixed-navbar pace-done menu-hide',
			css_nav_top: 'TOP header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-dark bg-primary navbar-shadow navbar-brand-center',
			css_nav_left: 'LEFT main-menu material-menu menu-fixed menu-light menu-accordion menu-shadow menu-border',
			css_nav_right: '',
		},
		style9: {
			css_theme_style: 'horizontal-menu-template',
			css_theme_file: '/assets/app-assets/css/core/menu/menu-types/material-horizontal-menu.css',
			css_body: 'BODY STYLE9 horizontal-layout horizontal-menu-padding material-horizontal-layout material-layout 2-columns pace-done menu-hide vertical-layout vertical-overlay-menu fixed-navbar',
			css_nav_top: 'TOP header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow navbar-static-top navbar-light navbar-brand-center fixed-top',
			css_nav_left: 'LEFT main-menu menu-light menu-fixed menu-shadow',
			css_nav_right: '',
		},
		style10: {
			css_theme_style: 'material-horizontal-menu-template',
			css_theme_file: '/assets/app-assets/css/core/menu/menu-types/material-horizontal-menu.css',
			css_body: 'BODY STYLE10 horizontal-layout horizontal-menu-padding material-horizontal-layout material-layout 2-columns pace-done menu-hide vertical-layout vertical-overlay-menu fixed-navbar',
			css_nav_top: 'TOP header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow navbar-static-top navbar-light navbar-brand-center fixed-top',
			css_nav_left: 'LEFT main-menu menu-light menu-fixed menu-shadow',
			css_nav_right: '',
		}
	}
}